name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: 'package.json'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install
  
    - name: Build project
      run: pnpm build

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: 'package.json'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install
  
    # - name: Run tests
    #   run: npm test

  code_quality:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
          
      - name: Run Biome
        run: biome ci .
